// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8A8NeTRLTnKg_ZfoNbKHf4ullQNMmrV4',
    appId: '1:812612591512:web:0865d80899f4b6e3f6d5ed',
    messagingSenderId: '812612591512',
    projectId: 'streak-create_battle',
    authDomain: 'streak-create_battle.firebaseapp.com',
    storageBucket: 'streak-create_battle.firebasestorage.app',
    measurementId: 'G-D1J3D12DPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuMMbe2SnZ2ZA3up_KF8YHSwC4AyCo50w',
    appId: '1:812612591512:android:e1b5e5eb1912f863f6d5ed',
    messagingSenderId: '812612591512',
    projectId: 'streak-create_battle',
    storageBucket: 'streak-create_battle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaA_55PFtotGbcpyPzoBBKp824OBDK6HY',
    appId: '1:812612591512:ios:a8db87d639463c2ef6d5ed',
    messagingSenderId: '812612591512',
    projectId: 'streak-create_battle',
    storageBucket: 'streak-create_battle.firebasestorage.app',
    iosClientId: '812612591512-02bhilt2a2jll7hjd8e39ltgtt1bq6et.apps.googleusercontent.com',
    iosBundleId: 'com.example.streakBattle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8A8NeTRLTnKg_ZfoNbKHf4ullQNMmrV4',
    appId: '1:812612591512:web:268eebd2c9ab29d7f6d5ed',
    messagingSenderId: '812612591512',
    projectId: 'streak-create_battle',
    authDomain: 'streak-create_battle.firebaseapp.com',
    storageBucket: 'streak-create_battle.firebasestorage.app',
    measurementId: 'G-V8Y575Y4G9',
  );
}
